# DO NOT EDIT THIS FILE, IT IS GENERATED
#
# To change the contents of this file, edit
# phpBB/develop/create_schema_files.php and
# run it.

# Table: 'phpbb_karma'
CREATE TABLE phpbb_karma (
	karma_id INTEGER NOT NULL,
	karma_type_id INTEGER DEFAULT 0 NOT NULL,
	item_id INTEGER DEFAULT 0 NOT NULL,
	giving_user_id INTEGER DEFAULT 0 NOT NULL,
	receiving_user_id INTEGER DEFAULT 0 NOT NULL,
	karma_score INTEGER DEFAULT 0 NOT NULL,
	karma_time INTEGER DEFAULT 0 NOT NULL,
	karma_comment BLOB SUB_TYPE TEXT CHARACTER SET UTF8 DEFAULT '' NOT NULL,
	karma_reported INTEGER DEFAULT 0 NOT NULL
);;

ALTER TABLE phpbb_karma ADD PRIMARY KEY (karma_id);;


CREATE GENERATOR phpbb_karma_gen;;
SET GENERATOR phpbb_karma_gen TO 0;;

CREATE TRIGGER t_phpbb_karma FOR phpbb_karma
BEFORE INSERT
AS
BEGIN
	NEW.karma_id = GEN_ID(phpbb_karma_gen, 1);
END;;


# Table: 'phpbb_karma_types'
CREATE TABLE phpbb_karma_types (
	karma_type_id INTEGER NOT NULL,
	karma_type_name VARCHAR(255) CHARACTER SET NONE DEFAULT '' NOT NULL,
	karma_type_enabled INTEGER DEFAULT 0 NOT NULL
);;

ALTER TABLE phpbb_karma_types ADD PRIMARY KEY (karma_type_id);;


CREATE GENERATOR phpbb_karma_types_gen;;
SET GENERATOR phpbb_karma_types_gen TO 0;;

CREATE TRIGGER t_phpbb_karma_types FOR phpbb_karma_types
BEFORE INSERT
AS
BEGIN
	NEW.karma_type_id = GEN_ID(phpbb_karma_types_gen, 1);
END;;


# Table: 'phpbb_karma_reports'
CREATE TABLE phpbb_karma_reports (
	karma_report_id INTEGER NOT NULL,
	karma_id INTEGER DEFAULT 0 NOT NULL,
	reporter_id INTEGER DEFAULT 0 NOT NULL,
	karma_report_closed INTEGER DEFAULT 0 NOT NULL,
	karma_report_time INTEGER DEFAULT 0 NOT NULL,
	karma_report_text BLOB SUB_TYPE TEXT CHARACTER SET UTF8 DEFAULT '' NOT NULL,
	reported_karma_score INTEGER DEFAULT 0 NOT NULL,
	reported_karma_time INTEGER DEFAULT 0 NOT NULL,
	reported_karma_comment BLOB SUB_TYPE TEXT CHARACTER SET UTF8 DEFAULT '' NOT NULL
);;

ALTER TABLE phpbb_karma_reports ADD PRIMARY KEY (karma_report_id);;


CREATE GENERATOR phpbb_karma_reports_gen;;
SET GENERATOR phpbb_karma_reports_gen TO 0;;

CREATE TRIGGER t_phpbb_karma_reports FOR phpbb_karma_reports
BEFORE INSERT
AS
BEGIN
	NEW.karma_report_id = GEN_ID(phpbb_karma_reports_gen, 1);
END;;


# Table: 'phpbb_users'
ALTER TABLE phpbb_users ADD "USER_KARMA_SCORE"  INTEGER DEFAULT 0 NOT NULL

