/*
 * DO NOT EDIT THIS FILE, IT IS GENERATED
 *
 * To change the contents of this file, edit
 * phpBB/develop/create_schema_files.php and
 * run it.
 */

/*
	Table: 'phpbb_karma'
*/
CREATE TABLE [phpbb_karma] (
	[karma_id] [int] IDENTITY (1, 1) NOT NULL ,
	[karma_type_id] [int] DEFAULT (0) NOT NULL ,
	[item_id] [int] DEFAULT (0) NOT NULL ,
	[giving_user_id] [int] DEFAULT (0) NOT NULL ,
	[receiving_user_id] [int] DEFAULT (0) NOT NULL ,
	[karma_score] [int] DEFAULT (0) NOT NULL ,
	[karma_time] [int] DEFAULT (0) NOT NULL ,
	[karma_comment] [varchar] (4000) DEFAULT ('') NOT NULL ,
	[karma_reported] [int] DEFAULT (0) NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [phpbb_karma] WITH NOCHECK ADD 
	CONSTRAINT [PK_phpbb_karma] PRIMARY KEY  CLUSTERED 
	(
		[karma_id]
	)  ON [PRIMARY] 
GO


/*
	Table: 'phpbb_karma_types'
*/
CREATE TABLE [phpbb_karma_types] (
	[karma_type_id] [int] IDENTITY (1, 1) NOT NULL ,
	[karma_type_name] [varchar] (255) DEFAULT ('') NOT NULL ,
	[karma_type_enabled] [int] DEFAULT (0) NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [phpbb_karma_types] WITH NOCHECK ADD 
	CONSTRAINT [PK_phpbb_karma_types] PRIMARY KEY  CLUSTERED 
	(
		[karma_type_id]
	)  ON [PRIMARY] 
GO


/*
	Table: 'phpbb_karma_reports'
*/
CREATE TABLE [phpbb_karma_reports] (
	[karma_report_id] [int] IDENTITY (1, 1) NOT NULL ,
	[karma_id] [int] DEFAULT (0) NOT NULL ,
	[reporter_id] [int] DEFAULT (0) NOT NULL ,
	[karma_report_closed] [int] DEFAULT (0) NOT NULL ,
	[karma_report_time] [int] DEFAULT (0) NOT NULL ,
	[karma_report_text] [varchar] (4000) DEFAULT ('') NOT NULL ,
	[reported_karma_score] [int] DEFAULT (0) NOT NULL ,
	[reported_karma_time] [int] DEFAULT (0) NOT NULL ,
	[reported_karma_comment] [varchar] (4000) DEFAULT ('') NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [phpbb_karma_reports] WITH NOCHECK ADD 
	CONSTRAINT [PK_phpbb_karma_reports] PRIMARY KEY  CLUSTERED 
	(
		[karma_report_id]
	)  ON [PRIMARY] 
GO


/*
	Table: 'phpbb_users'
*/
ALTER TABLE [phpbb_users] ADD [user_karma_score]  [int] DEFAULT (0) NOT NULL

