# DO NOT EDIT THIS FILE, IT IS GENERATED
#
# To change the contents of this file, edit
# phpBB/develop/create_schema_files.php and
# run it.
# Table: 'phpbb_karma'
CREATE TABLE phpbb_karma (
	karma_id mediumint(8) UNSIGNED NOT NULL auto_increment,
	karma_type_id mediumint(8) UNSIGNED DEFAULT '0' NOT NULL,
	item_id mediumint(8) UNSIGNED DEFAULT '0' NOT NULL,
	giving_user_id mediumint(8) UNSIGNED DEFAULT '0' NOT NULL,
	receiving_user_id mediumint(8) UNSIGNED DEFAULT '0' NOT NULL,
	karma_score tinyint(4) DEFAULT '0' NOT NULL,
	karma_time int(11) UNSIGNED DEFAULT '0' NOT NULL,
	karma_comment blob NOT NULL,
	karma_reported tinyint(1) UNSIGNED DEFAULT '0' NOT NULL,
	PRIMARY KEY (karma_id)
);


# Table: 'phpbb_karma_types'
CREATE TABLE phpbb_karma_types (
	karma_type_id mediumint(8) UNSIGNED NOT NULL auto_increment,
	karma_type_name varbinary(255) DEFAULT '' NOT NULL,
	karma_type_enabled tinyint(1) UNSIGNED DEFAULT '0' NOT NULL,
	PRIMARY KEY (karma_type_id)
);


# Table: 'phpbb_karma_reports'
CREATE TABLE phpbb_karma_reports (
	karma_report_id mediumint(8) UNSIGNED NOT NULL auto_increment,
	karma_id mediumint(8) UNSIGNED DEFAULT '0' NOT NULL,
	reporter_id mediumint(8) UNSIGNED DEFAULT '0' NOT NULL,
	karma_report_closed tinyint(1) UNSIGNED DEFAULT '0' NOT NULL,
	karma_report_time int(11) UNSIGNED DEFAULT '0' NOT NULL,
	karma_report_text blob NOT NULL,
	reported_karma_score tinyint(4) DEFAULT '0' NOT NULL,
	reported_karma_time int(11) UNSIGNED DEFAULT '0' NOT NULL,
	reported_karma_comment blob NOT NULL,
	PRIMARY KEY (karma_report_id)
);


# Table: 'phpbb_users'
ALTER TABLE `phpbb_users` ADD COLUMN `user_karma_score`  int(11) DEFAULT '0' NOT NULL;

