/*
 * DO NOT EDIT THIS FILE, IT IS GENERATED
 *
 * To change the contents of this file, edit
 * phpBB/develop/create_schema_files.php and
 * run it.
 */


/*
	Table: 'phpbb_karma'
*/
CREATE TABLE phpbb_karma (
	karma_id number(8) NOT NULL,
	karma_type_id number(8) DEFAULT '0' NOT NULL,
	item_id number(8) DEFAULT '0' NOT NULL,
	giving_user_id number(8) DEFAULT '0' NOT NULL,
	receiving_user_id number(8) DEFAULT '0' NOT NULL,
	karma_score number(4) DEFAULT '0' NOT NULL,
	karma_time number(11) DEFAULT '0' NOT NULL,
	karma_comment clob DEFAULT '' ,
	karma_reported number(1) DEFAULT '0' NOT NULL,
	CONSTRAINT pk_phpbb_karma PRIMARY KEY (karma_id)
)
/


CREATE SEQUENCE phpbb_karma_seq
/

CREATE OR REPLACE TRIGGER t_phpbb_karma
BEFORE INSERT ON phpbb_karma
FOR EACH ROW WHEN (
	new.karma_id IS NULL OR new.karma_id = 0
)
BEGIN
	SELECT phpbb_karma_seq.nextval
	INTO :new.karma_id
	FROM dual;
END;
/


/*
	Table: 'phpbb_karma_types'
*/
CREATE TABLE phpbb_karma_types (
	karma_type_id number(8) NOT NULL,
	karma_type_name varchar2(255) DEFAULT '' ,
	karma_type_enabled number(1) DEFAULT '0' NOT NULL,
	CONSTRAINT pk_phpbb_karma_types PRIMARY KEY (karma_type_id)
)
/


CREATE SEQUENCE phpbb_karma_types_seq
/

CREATE OR REPLACE TRIGGER t_phpbb_karma_types
BEFORE INSERT ON phpbb_karma_types
FOR EACH ROW WHEN (
	new.karma_type_id IS NULL OR new.karma_type_id = 0
)
BEGIN
	SELECT phpbb_karma_types_seq.nextval
	INTO :new.karma_type_id
	FROM dual;
END;
/


/*
	Table: 'phpbb_karma_reports'
*/
CREATE TABLE phpbb_karma_reports (
	karma_report_id number(8) NOT NULL,
	karma_id number(8) DEFAULT '0' NOT NULL,
	reporter_id number(8) DEFAULT '0' NOT NULL,
	karma_report_closed number(1) DEFAULT '0' NOT NULL,
	karma_report_time number(11) DEFAULT '0' NOT NULL,
	karma_report_text clob DEFAULT '' ,
	reported_karma_score number(4) DEFAULT '0' NOT NULL,
	reported_karma_time number(11) DEFAULT '0' NOT NULL,
	reported_karma_comment clob DEFAULT '' ,
	CONSTRAINT pk_phpbb_karma_reports PRIMARY KEY (karma_report_id)
)
/


CREATE SEQUENCE phpbb_karma_reports_seq
/

CREATE OR REPLACE TRIGGER t_phpbb_karma_reports
BEFORE INSERT ON phpbb_karma_reports
FOR EACH ROW WHEN (
	new.karma_report_id IS NULL OR new.karma_report_id = 0
)
BEGIN
	SELECT phpbb_karma_reports_seq.nextval
	INTO :new.karma_report_id
	FROM dual;
END;
/


/*
	Table: 'phpbb_users'
*/
ALTER TABLE phpbb_users ADD user_karma_score  number(11) DEFAULT '0' 

