/*
 * DO NOT EDIT THIS FILE, IT IS GENERATED
 *
 * To change the contents of this file, edit
 * phpBB/develop/create_schema_files.php and
 * run it.
 */

BEGIN;


/*
	Table: 'phpbb_karma'
*/
CREATE SEQUENCE phpbb_karma_seq;

CREATE TABLE phpbb_karma (
	karma_id INT4 DEFAULT nextval('phpbb_karma_seq'),
	karma_type_id INT4 DEFAULT '0' NOT NULL CHECK (karma_type_id >= 0),
	item_id INT4 DEFAULT '0' NOT NULL CHECK (item_id >= 0),
	giving_user_id INT4 DEFAULT '0' NOT NULL CHECK (giving_user_id >= 0),
	receiving_user_id INT4 DEFAULT '0' NOT NULL CHECK (receiving_user_id >= 0),
	karma_score INT2 DEFAULT '0' NOT NULL,
	karma_time INT4 DEFAULT '0' NOT NULL CHECK (karma_time >= 0),
	karma_comment varchar(4000) DEFAULT '' NOT NULL,
	karma_reported INT2 DEFAULT '0' NOT NULL CHECK (karma_reported >= 0),
	PRIMARY KEY (karma_id)
);


/*
	Table: 'phpbb_karma_types'
*/
CREATE SEQUENCE phpbb_karma_types_seq;

CREATE TABLE phpbb_karma_types (
	karma_type_id INT4 DEFAULT nextval('phpbb_karma_types_seq'),
	karma_type_name varchar(255) DEFAULT '' NOT NULL,
	karma_type_enabled INT2 DEFAULT '0' NOT NULL CHECK (karma_type_enabled >= 0),
	PRIMARY KEY (karma_type_id)
);


/*
	Table: 'phpbb_karma_reports'
*/
CREATE SEQUENCE phpbb_karma_reports_seq;

CREATE TABLE phpbb_karma_reports (
	karma_report_id INT4 DEFAULT nextval('phpbb_karma_reports_seq'),
	karma_id INT4 DEFAULT '0' NOT NULL CHECK (karma_id >= 0),
	reporter_id INT4 DEFAULT '0' NOT NULL CHECK (reporter_id >= 0),
	karma_report_closed INT2 DEFAULT '0' NOT NULL CHECK (karma_report_closed >= 0),
	karma_report_time INT4 DEFAULT '0' NOT NULL CHECK (karma_report_time >= 0),
	karma_report_text varchar(4000) DEFAULT '' NOT NULL,
	reported_karma_score INT2 DEFAULT '0' NOT NULL,
	reported_karma_time INT4 DEFAULT '0' NOT NULL CHECK (reported_karma_time >= 0),
	reported_karma_comment varchar(4000) DEFAULT '' NOT NULL,
	PRIMARY KEY (karma_report_id)
);


/*
	Table: 'phpbb_users'
*/
ALTER TABLE phpbb_users ADD COLUMN "user_karma_score" INT4 ;
ALTER TABLE phpbb_users ALTER COLUMN user_karma_score SET NOT NULL;
ALTER TABLE phpbb_users ALTER COLUMN user_karma_score SET DEFAULT '0';


COMMIT;
