# DO NOT EDIT THIS FILE, IT IS GENERATED
#
# To change the contents of this file, edit
# phpBB/develop/create_schema_files.php and
# run it.
BEGIN TRANSACTION;

# Table: 'phpbb_karma'
CREATE TABLE phpbb_karma (
	karma_id INTEGER PRIMARY KEY NOT NULL ,
	karma_type_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	item_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	giving_user_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	receiving_user_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	karma_score tinyint(4) NOT NULL DEFAULT '0',
	karma_time INTEGER UNSIGNED NOT NULL DEFAULT '0',
	karma_comment text(65535) NOT NULL DEFAULT '',
	karma_reported INTEGER UNSIGNED NOT NULL DEFAULT '0'
);


# Table: 'phpbb_karma_types'
CREATE TABLE phpbb_karma_types (
	karma_type_id INTEGER PRIMARY KEY NOT NULL ,
	karma_type_name varchar(255) NOT NULL DEFAULT '',
	karma_type_enabled INTEGER UNSIGNED NOT NULL DEFAULT '0'
);


# Table: 'phpbb_karma_reports'
CREATE TABLE phpbb_karma_reports (
	karma_report_id INTEGER PRIMARY KEY NOT NULL ,
	karma_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	reporter_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	karma_report_closed INTEGER UNSIGNED NOT NULL DEFAULT '0',
	karma_report_time INTEGER UNSIGNED NOT NULL DEFAULT '0',
	karma_report_text text(65535) NOT NULL DEFAULT '',
	reported_karma_score tinyint(4) NOT NULL DEFAULT '0',
	reported_karma_time INTEGER UNSIGNED NOT NULL DEFAULT '0',
	reported_karma_comment text(65535) NOT NULL DEFAULT ''
);


# Table: 'phpbb_users'
ALTER TABLE phpbb_users ADD user_karma_score [ int(11) NOT NULL DEFAULT '0']


COMMIT;
