imports:
    - { resource: parameters.yml }

services:
    karma.type_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: karma.type }

    karma.type.post:
        class: phpbb\karma\includes\type\type_post
        arguments:
            - @auth
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %tables.karma.karma%
        tags:
            - { name: karma.type }

    karma.includes.manager:
        class: phpbb\karma\includes\manager
        arguments:
            - @karma.type_collection
            - @cache
            - @service_container
            - @dbal.conn
            - @dispatcher
            - @controller.helper
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %tables.karma.karma%
            - %tables.karma.karma_types%

    karma.includes.report_model:
        class: phpbb\karma\includes\report_model
        arguments:
            - @dbal.conn
            - @user
            - @karma.includes.manager
            - %tables.karma.karma_reports%

    karma.controller.givekarma:
        class: phpbb\karma\controller\givekarma
        arguments:
            - @auth
            - @service_container
            - @request
            - @template
            - @user
            - @controller.helper

    karma.controller.reportkarma:
        class: phpbb\karma\controller\reportkarma
        arguments:
            - @service_container
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
